<?php

namespace App\Form\Type\Dropzone;

use App\Repository\ImgRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DropzoneType extends AbstractType
{
    public function __construct(
        private ImgRepository $imgRepository
    ) {
    }

    final public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'dropzone',
            CollectionType::class,
            [
                'entry_type' => HiddenType::class,
                'label' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'attr' => [
                    'class' => 'dropzone',
                    'id' => 'dropzone',
                    'action' => '/img/upload',
                ],
            ]
        )->addModelTransformer(new DropzoneTransformer($this->imgRepository));

        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    /**
     * @param OptionsResolver $resolver
     */
    final public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'maxFiles' => 1,
            'addRemoveLinks' => false,
            'resizeWidth' => 0,
            'resizeHeight' => 0,
        ]);

        parent::configureOptions($resolver);
    }

    /**
     * @param FormView $view
     * @param FormInterface $form
     * @param array $options
     */
    final public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        /** @var FormView $f */
        $f = $view->vars['form'];
        $view->vars['formName'] = $f->parent->vars['name'];
        $view->vars['id'] = $options['attr']['id'];
        $view->vars['maxFiles'] = $options['maxFiles'];
        $view->vars['img'] = [];
        $view->vars['addRemoveLinks'] = $options['addRemoveLinks'];
        $view->vars['resizeWidth'] = $options['resizeWidth'];
        $view->vars['resizeHeight'] = $options['resizeHeight'];

        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }
}